SET DATABASE SQL SYNTAX ORA TRUE;

-- IOSS_VAT_TAB --
DROP TABLE IF EXISTS "IOSS_VAT_TAB";

CREATE TABLE "IOSS_VAT_TAB"(
"ID" NUMBER,
"IOSS_VAT_ID" VARCHAR2(12 CHAR),
"VALIDITY_START_DATE" DATE,
"VALIDITY_END_DATE" DATE,
"CREATION_DATE" timestamp,
"UPDATED_DATE" timestamp,
"EU_MODIFICATION_DATE" timestamp,
CONSTRAINT IOSS_VAT_ID_UK UNIQUE ("IOSS_VAT_ID")
);
ALTER TABLE "IOSS_VAT_TAB" ADD CONSTRAINT "IOSS_PK" PRIMARY KEY ("ID");

DROP SEQUENCE IF EXISTS "IOSS_VAT_TAB_SEQ";
CREATE SEQUENCE IOSS_VAT_TAB_SEQ MINVALUE 1 MAXVALUE 999 INCREMENT BY 1 START WITH 1 CACHE 20;

-- IOSS_VAT_AUDIT_TAB --
DROP TABLE IF EXISTS "IOSS_VAT_AUDIT_TAB";
CREATE TABLE "IOSS_VAT_AUDIT_TAB"
("IOSS_VAT_ID" VARCHAR2(12 CHAR) NOT NULL,
"VALIDITY_START_DATE" DATE,
"VALIDITY_END_DATE" DATE,
"EU_MODIFICATION_DATE" timestamp,
"OPERATION" CHAR(1 CHAR) NOT NULL,
"OUTCOME" NUMBER(1) NOT NULL,
"AUDIT_DATE" timestamp NOT NULL,
"REMARKS" VARCHAR2(500 CHAR)
);